name: release
on:
  pull_request:
    branches: ["main"]
  push:
    tags:
    - '*'


jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./merkle-store-hardhat
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn
      - run: npx hardhat compile

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/contracts/UpgradableMerkleStoreV1.sol/UpgradableMerkleStoreV1.json
